name: hh_refresh
description: "Head hunter reminder app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  universal_platform: ^1.1.0
  streaming_shared_preferences: ^2.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  go_router: ^14.7.1
  rx_shared_preferences: ^4.0.0
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^18.0.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
